# Generated by Django 4.1 on 2023-09-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_roll', models.CharField(max_length=150)),
                ('m_name', models.CharField(max_length=150)),
                ('m_email', models.CharField(max_length=150)),
                ('m_adress', models.CharField(max_length=150)),
                ('m_phone', models.CharField(max_length=150)),
            ],
        ),
    ]
